server:
  port: 8020
spring:
  cloud:
    client:
      ipAddress: 192.168.3.30
  application:
    name: service-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.30:8005/eureka/ #http://192.168.3.22:8005/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url-path: /index.html #配置在注册中心界面服务列表的Status列点击跳转到项目用